pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage('Checkout SCM'){
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/howdycloudyarsh/Sprint_2/tree/main/Task%202']])
                }
            }
        }
        stage('Initializing Terraform'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Formatting Terraform Files'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform fmt'
                    }
                }
            }
        }
        stage('Validating Terraform Files'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('Viewing Infra Using Terraform'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform plan'
                    }
                }
            }
        }
        stage('Provisioning EKS Cluster'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform apply --auto-approve'
                    }
                }
            }
        }
        stage('Deleting EKS Cluster'){
            steps{
                script{
                    dir('Task 2/EKS'){
                        sh 'terraform init'
                        sh 'terraform destroy --auto-approve'
                    }
                }
            }
        }
        
    }
}



